// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aahutWffs1FlR8q_VWG8OOQwmvV7KK4',
    appId: '1:1068578624173:web:bf640c69c3714c79f96c24',
    messagingSenderId: '1068578624173',
    projectId: 'shoppinglistapp-2b0f4',
    authDomain: 'shoppinglistapp-2b0f4.firebaseapp.com',
    storageBucket: 'shoppinglistapp-2b0f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CcN7sJnS-xi9J3d_BC83NIot2buayAw',
    appId: '1:1068578624173:android:55f5d08bb79d0433f96c24',
    messagingSenderId: '1068578624173',
    projectId: 'shoppinglistapp-2b0f4',
    storageBucket: 'shoppinglistapp-2b0f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1v5tTUBe65fzcOfvSa02lM82rqrakYTg',
    appId: '1:1068578624173:ios:5a10d20ef5e6cc48f96c24',
    messagingSenderId: '1068578624173',
    projectId: 'shoppinglistapp-2b0f4',
    storageBucket: 'shoppinglistapp-2b0f4.appspot.com',
    iosClientId: '1068578624173-mcjgcfs62coltk5dbd5usk0ohtsfmmc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.l5Iot',
  );
}
